spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/H2/snakehouse/snakehouse
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  redis:
    host: 192.168.99.100
    port: 6379
logging:
  level:
    org.hibernte.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

#
#server:
#  servlet:
#    context-path: /snakehouse